# Generated by Django 5.2.1 on 2026-04-08 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_alternate_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='alternate_phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_daily',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_dl',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_monthly',
        ),
    ]
