# Generated by Django 5.2.1 on 2026-05-06 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_customer_alternate_phone_and_more'),
        ('organizations', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='organizations.organization'),
        ),
    ]
