# Generated by Django 5.2.1 on 2026-02-03 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='amount',
            new_name='principal_amount',
        ),
        migrations.AddField(
            model_name='loan',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('settled', 'Settled'), ('overdue', 'Overdue')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='asal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='interest_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('DC Loan', 'DC Loan'), ('Monthly Interest Loan', 'Monthly Interest Loan'), ('DL Loan', 'DL Loan')], max_length=25),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('transfer', 'Bank Transfer'), ('check', 'Check')], default='cash', max_length=20),
        ),
    ]
