# Generated by Django 5.2.1 on 2026-02-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_rename_amount_loan_principal_amount_loan_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='allow_asal_payment_anytime',
            field=models.BooleanField(default=True, help_text='Allow principal payment anytime for DL loan'),
        ),
        migrations.AddField(
            model_name='loan',
            name='daily_collection_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Daily collection amount', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='daily_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Daily interest rate percentage', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='expected_total_days',
            field=models.PositiveIntegerField(blank=True, help_text='Expected total days for completion', null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='interest_cycle_day',
            field=models.PositiveIntegerField(blank=True, help_text='Day of month when interest is due', null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='max_days',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum days for loan completion', null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='monthly_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly interest rate percentage', max_digits=5, null=True),
        ),
    ]
