# Generated by Django 5.2.1 on 2026-02-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_loan_allow_asal_payment_anytime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('gpay', 'GPay'), ('card', 'Card'), ('transfer', 'Bank Transfer'), ('check', 'Check')], default='cash', max_length=20),
        ),
    ]
