# Generated by Django 5.2.1 on 2026-02-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transaction_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='pending_interest',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Unpaid interest from previous cycles', max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], default='cash', max_length=20),
        ),
    ]
