# Generated by Django 5.2.1 on 2026-02-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_loan_pending_interest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='last_interest_date',
            field=models.DateField(blank=True, help_text='Date when interest was last calculated/paid', null=True),
        ),
    ]
