# Generated by Django 5.2.1 on 2026-03-15 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_loan_dc_deduction_amount_dailycashbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='last_interest_date',
        ),
    ]
