# Generated by Django 5.2.1 on 2026-04-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_remove_loan_last_interest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('settled', 'Settled')], default='active', max_length=20),
        ),
    ]
