# Generated by Django 5.2.1 on 2026-05-06 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '__first__'),
        ('transactions', '0012_alter_loan_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycashbook',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashbook_entries', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='loan',
            name='closed_at',
            field=models.DateTimeField(blank=True, help_text='When the loan was manually closed/written off', null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='closure_note',
            field=models.TextField(blank=True, help_text="Admin's reason for closing the loan", null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_edited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_edited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dailycashbook',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('settled', 'Settled'), ('closed', 'Closed')], default='active', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='dailycashbook',
            unique_together={('date', 'organization')},
        ),
    ]
