# Generated by Django 5.2.1 on 2025-05-15 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['created_at'], name='expenses_ex_created_52941d_idx'),
        ),
    ]
