# Generated by Django 5.2.1 on 2026-03-15 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_expensecategory_income_expense_category'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='income',
            new_name='expenses_in_created_4e6a9d_idx',
            old_name='expenses_in_created_idx',
        ),
    ]
