# Generated by Django 5.2.1 on 2026-05-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '__first__'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organizations',
            field=models.ManyToManyField(blank=True, help_text='Organizations this user has access to', related_name='users', to='organizations.organization'),
        ),
    ]
